name: my_filter_camera
description: "This package lets you use the camera with advanced digital filters, apply real-time effects, and customize your camera experience easily."
version: 1.0.4+1
maintainers:
  - "Ducnguyen (Wong) <ngmduc2012@gmail.com>"
repository: https://github.com/ngmduc2012/my_filter_camera

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.wongcoupon.my_filter_camera
        pluginClass: MyFilterCamera
      ios:
        pluginClass: MyFilterCamera

screenshots:
  - description: "avatar plugin"
    path: avatar.png

topics:
  - camera
  - photo-filters
  - real-time-effects
  - photography
  - media

